version: '3'

services:
  python-template:
    image: python-template:production
    hostname: python-template
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      secrets:
        - aws
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}

secrets:
  aws:
    file: ${HOME}/.aws/credentials