version: '3'

services:
  python-template:
    extends:
      file: docker-compose.yml
      service: python-template
    image: python-template:lambda
    build:
      target: lambda
      secrets:
        - aws

secrets:
  aws:
    file: ${HOME}/.aws/credentials