version: '3'

services:
  python-template:
    image: python-template:production
    hostname: python-template
    build:
      context: .
      ssh:
        - default
      dockerfile: Dockerfile
      target: production
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
