version: '3'

services:
  python-template:
    image: python-template
    hostname: python-template
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - aws
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    volumes:
      - ./:/home/worker/code
      - ${HOME}/.aws:/home/worker/.aws:ro
      - /home/worker/code/.venv

secrets:
  aws:
    file: ${HOME}/.aws/credentials