version: '3'

services:
  python-template:
    extends:
      file: docker-compose.yml
      service: python-template
    image: python-template:development
    build:
      target: development
    volumes:
      - ./:/home/antipodestudios/code
      - ~/.ssh:/home/antipodestudios/.ssh
