version: '3'

services:
  python-template:
    extends:
      file: docker-compose.yml
      service: python-template
    image: python-template:development
    build:
      target: development
      secrets:
        - aws
    volumes:
      - ./:/home/worker/code
      - ${HOME}/.aws:/home/worker/.aws:ro
      - /home/worker/code/.venv

secrets:
  aws:
    file: ${HOME}/.aws/credentials