[tool.poetry]
name = "python-template"
version = "1.0.0"
description = ""
authors = ["Adem Usta <adem@adem.sh>"]
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.4"
black = "^22.8.0"
pytest = "^7.1.3"
pyright = "^1.1.273"
coverage = {extras = ["toml"], version = "^6.5.0"}
pytest-cov = "^4.0.0"
ipython = "^8.5.0"
poethepoet = "^0.16.4"

[tool.poe.tasks]
tests = "coverage run -m pytest"
coverage = "coverage report -m"
lint = "pylint app"
format = "black app --check"
type-check = "pyright app"

[tool.black]
line-length = 100

[tool.pylint.messages_control]
max-line-length = 100
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
]

[tool.pyright]
include = ["app"]

[tool.coverage.run]
omit = [".*", "*/site-packages/*", "*__init__*", "*__main__*"]
source = ["app"]

[tool.coverage.report]
fail_under = 100


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
