name: "Bump New Version"

on:
  push:
    tags:
      - "v*"

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Changelog
        run: |
          wget -O archive.tar.gz https://github.com/git-chglog/git-chglog/releases/download/v0.15.1/git-chglog_0.15.1_linux_amd64.tar.gz
          tar -xf archive.tar.gz
          ./git-chglog
