name: Branches Checks

on:
  pull_request:
    branches: [develop]

jobs:
  commits-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5