name: pre-release-workflow

on:
  pull_request:
    branches: [master]

jobs:
  commits-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  code-quality-checkers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ANTIPODE_BOT_PRIVATE_KEY}}
      - name: update-docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: BUILD
        run: make build
      - name: CODE QUALITY
        run: make code-quality
      - name: UNIT TESTS
        run: make unit-tests
      - name: INTEGRATION TESTS
        run: make integration-tests