name: next-release-workflow

on: [workflow_dispatch]

jobs:
  publish-next-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build-image
        run: make build
      - name: run-publish
        run: make next_release
        env:
          GITHUB_TOKEN: ${{ github.token }}