name: Next release

on: [workflow_dispatch]

jobs:
  publish-next-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Image
        run: make build
      - name: Run publish
        run: make next_release