name: next-release-workflow

on: [workflow_dispatch]

jobs:
  publish-next-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: update-docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: build-image
        run: make build
      - name: run-publish
        run: make next_release
        env:
          GITHUB_TOKEN: ${{ github.token }}