name: Template Release Workflow

on: [workflow_dispatch]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
      - name: publish-next-release
        run: |
            pip install python-semantic-release
            semantic-release version --no-vcs-release --skip-build
        env:
          GH_TOKEN: ${{ github.token }}